### ISSUE TITLE
Check again import Process, newly created Scales, Feedback

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#152]
@eynimeni Try the whole process on a clean install again, make sure everything works.
 
@semteacher wait until the OK from Magdalena, then create the following test:
- [x] Import of questions (start with Mathematik, from the zip file)
- [x] Go to manage catscales, import via importer on "import" Tab in manage_catscales.php
- [x] There should be no errors.
- [x] Go to catscales tab, check if scales were created.
- [x] Go on questions tab, check if questions are imported.
- [x] Search for one particular question via fullext search.
- [x] Check for this question if difficulty, discrimination and guessing is correctly implemented.

**Comment by georgmaisser** [comment]
[Test - Alise Demonstrator Test questions.zip](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12735441/Test.-.Alise.Demonstrator.Test.questions.zip)

**Comment by semteacher** [comment]
Choice of test type:
- description of process of import of catscale - points that usage of behat test is most recommended.
- however import of questions itself via behat will take time due to amout of questions (86 and 76 in given fixture docs). 
Suggestion: to create fixtures with minimum info:
- no more than 2 catscales
- no more than 3-4 questions to import
Another way is to import questions in "background" mode. Could be preferable but
- it looks like there is no generator method exists for this case for now
- development possible but take some time (4-6 hours min)

**Comment by eynimeni** [comment]
I made a short version as suggested for you, with only 2 scales and three questions. 
In the folder you can also find a longer version with more data that shouldn't throw any errors.
[importfiles_short.zip](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/files/12762090/importfiles_short.zip)
