### ISSUE TITLE
Bugfix Quizattempt Feedback reporting error

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#157]
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/08d2605a-eb6a-4717-9c7d-f21db0126780)

When DB like this (with values in json), no error occurs, attempts are saved and displayed in attempts table
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/a9a5f976-e730-43c8-9b04-16825ca205c0)

**Comment by davidszkiba** [comment]
This should already be fixed with https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/commit/561fc3d45b359032513ee2751bef9f2fa11a1e06 
The problem was, that one particular feedback generator converted the `$quizsettings` attempdata value to an array, so accessing quizsettings as an object failed in that case. See the linked commit for more details.
