### ISSUE TITLE
JS Error for question preview rendering in behat (invisible questions)

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#277]
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/78353570/f43c0f59-72ce-4a17-a8c8-3652639ccff4)

- [ ] avoid error - disable js in rendered question preview
- [ ] check if question preview is the best way
- [ ] avoid "not yet answered"

**Comment by georgmaisser** [comment]
The reason is the following:

In attempt feedback 160, the generators are called to generate feedback data.
Here, render_questionpreview is already executed, but the questions are never actually printed to the screen.

But when you call render, the JS is added to the footer. So, the JS for the never rendered questions is executed, which leads to the errors.

I ask myself if the "load_data_from_generators' and the generate_feedback are redundant as they generate the preview twice.

It should be possible to check feedback data if the preview is already here and not recreate it. This would solve our problem:

attemptfeedback line 160
`$feedbackdata = $this->load_data_from_generators($generators, $context);
        if (!$feedbackdata) {
            return [];
        }

        // If courses or groups are selected, User is enrolled to.
        catquiz::enrol_user($USER->id, (array)$cache->get('quizsettings'), (array)$cache->get('personabilities'));

        if ($savetodb) {
            $id = catquiz::save_attempt_to_db($feedbackdata);
        }
        return $this->generate_feedback($generators, $feedbackdata);`
