### ISSUE TITLE
define behat and unit tests for interface

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_catquiz#351]
Check that page reload logic works as expected

- [x] If I start a quiz, reload the page, I see the same question again
- [x] If I wait until the maximum time per item is exceeded and I reload the page, I should see a different question
- [x] If I start a quiz, log out, log back in and resume the quiz, I should see the last question again (given the timeout is not exceeded)
- [x] If I start a quiz and wait until the maximum time per item is exceeded, log out and log back in and resume the quiz, I should see a different question.

Check that the quiz timeout works

- [x] If I set the maximum attempt time to 1 minute, start a quiz and let that timeout exceed, the quiz should stop when I answer the first question and I should see the timeout exceeded message

**Comment by semteacher** [comment]
This seems to be difficult / barely possible with behat.
- "If I start a quiz, reload the page, I see the same question again". Based on curent experience - I do not see existing way to get current question features (ID, text) to compare with ones after page being reloaded. I can imagine possibility to develop a custom steps - but it still necessary to pass data between steps somehow (in session variables? or try to access quiz attemp data in DB?)... 
I can  
- "If I set the maximum attempt time to 1 minute..."  in addition to all above difficulties - this one will increase testing time significantly - exactly because of 1 min waiting time per each run (DB/php/moodle version). And thre are few such scenarios available.

**Comment by eynimeni** [comment]
thank you @semteacher !

- With the same quizsettings, there should always be the same question selected. So maybe you can check before and after refreshment for the questiontext (for example: then i should see "Schwierigkeit: -0.96 Trennschärtfe: 5.35 Skala: C/C01") 
and then recheck after page reload?

- we are aware that this waiting 1min each time will slow down tests a lot. still it's an important function, so we need to test it...

**Comment by semteacher** [comment]
Item 3, "If I start a quiz, log out, log back in and resume the quiz, I should see the last question again (given the timeout is not exceeded)" does not works this way
- settings
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/71c8d862-e5cd-47d0-a4c3-9451a27f5f3b)
- 2nd question of 1st attempt
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/badcd003-048d-4aad-965f-da2891e4d534)
- after relogin (Button always "start attempt" - no "continue attempt") 
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/ed78fb48-b263-47ae-85dd-3242417c4b0e)
- 2nd question displayed but it is different than previous
![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/1571998/6cd702cd-46ca-40a5-bc5d-a2724cbf5a6b)

So I have created a Scenario: Start adaptive quiz attempt and relogin on second page without item timeout
It fails now but will pass OK after above issue will be fixed

**Comment by eynimeni** [comment]
@davidszkiba please have a look at this

**Comment by semteacher** [comment]
In fact - that behat test passde OK at GitHub... 
But failed on my dev under Moodle 4.3/php 8.2

**Comment by semteacher** [comment]
@davidszkiba I have prepared new scenario "Start adaptive quiz attempt wait quiz timeout and submit answer" to cover 
" If I set the maximum attempt time to 1 minute, start a quiz and let that timeout exceed, the quiz should stop when I answer the first question and I should see the timeout exceeded message"
but it fails locally - after exceeding of 1 min (or even more) when I submit 1st question - I see 2nd and so on...

**Comment by davidszkiba** [comment]
@semteacher ok thank you. I checked and in the browser it is the same. I'll have a look and fix that.

**Comment by davidszkiba** [comment]
@semteacher The code that enforces the maximum attempt time was not yet merged. I just merged it into develop in PR-396
If you rebase your testing branch onto develop, the attempt timeout should work now.
Please note: it does not display a specific "timeout exceeded" message because I'm not sure how this message should be shown. Instead, the quiz attempt just stops in a regular way (as if the maximum number of questions is reached) and you should see the normal feedback.
I think your test should work fine now

**Comment by semteacher** [comment]
behat Scenario
Start adaptive quiz attempt wait quiz timeout and submit answer
passing OK under testing branch (on top of development) but failed under dev_testing_GH-294  because lack of sting (I have tried to megre that enforcing commit from GH-396)
I consider #351 as complete.

**Comment by davidszkiba** [comment]
@semteacher It looks like there is a typo in branch GH-294-apply-strategy-settings. I will try to fix it there and rebase the testing_GH-294 onto that change to make it green

**Comment by davidszkiba** [comment]
Actions are green now. I would let this issue open now and close it once the changes are merged into develop

**Comment by davidszkiba** [comment]
Closing since changes are now in develop
