### ISSUE TITLE
Images of questions are not displayed

### ISSUE THREAD

**Issue by davidszkiba** [Wunderbyte-GmbH/moodle-local_catquiz#68]
Some questions contain images and those are not displayed.

![image](https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/17564611/42dc17ee-70b7-481f-8ee6-95d7614a6a83)

**Comment by vtos** [comment]
@davidszkiba 
Hi David,

Sorry for breaking in, guys :slightly_smiling_face: , but this seems like a regression bug on the dedicated branch of the adaptive quiz which you're currently using. Because I noticed I cannot see images using the default algorithm as well. This has been fixed in the past though, but as I've told already seems like a regression. So, you can leave this issue for me to look into.
Cheers!

**Comment by davidszkiba** [comment]
@vtos 
Hi Vitaly,

Thanks for breaking in :smile:
Ok good, then I'll leave this to you and close the issue here.

**Comment by davidszkiba** [comment]
@vtos Great, thank you!
