### ISSUE TITLE
Going on question analysis in mod adaptive quiz with catquiz attempts leads to an error

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_catquiz#73]
We might need to make sure the standard error variable is present in mod adaptivequiz.

<img width="1385" alt="Bildschirmfoto 2023-07-19 um 08 51 40" src="https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/assets/7524621/2224cbb5-8fe1-4240-ba00-e87fab8e1b5a">

https://alise.wunderbyte.at/mod/adaptivequiz/questionanalysis/overview.php?cmid=4

**Comment by vtos** [comment]
@georgmaisser 
Hi Georg,

The correct approach would be to eliminate such links in the adaptive quiz mod itself, because they're related purely to the default CAT algorithm. I'll handle this soon from my side, as I'm currently doing some other changes in reporting in adaptive quiz to respect cases when a custom CAT model is used. You may keep this issues open and when I push some updates It may be then closed.

Cheers
Vitaly

**Comment by vtos** [comment]
@georgmaisser 
the changes have been pushed to both **catmodel_subplugins** branches, now the navigation link is not appearing and the relevant pages are not accessible when a custom CAT model is set for an adaptive quiz.

Cheers!
Vitaly

**Comment by davidszkiba** [comment]
Thanks @vtos :)
